[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "Iosevka"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 0.8
